### ISSUE TITLE
Research documentation library

### ISSUE THREAD

**Issue by cisso** [cisso/kayak#1]
We need to find a tool that will allow us to generate a queryable structure from Drupal's code base. Ideally it will also provide a pluggable UI.

**Comment by cisso** [comment]
A list of possible candidates: https://packagist.org/packages/nikic/php-parser/dependents

**Comment by cisso** [comment]
I went through all 17 pages of the above list and pulled the following results from them:
- [phpdox](https://github.com/theseer/phpdox): Converts to XML, transforms to HTML via XSLT (by default). Provides an API to detect and collect additional information. Uses *Enricher* plugins to add external data to the XML. Highly interesting.
- [phpDocumentor/Reflection](https://github.com/phpDocumentor/Reflection)
- [FriendsOfPHP/Sami](https://github.com/FriendsOfPHP/Sami)

Honorable mentions:
- The [Yii documentation](http://www.yiiframework.com/doc-2.0/) uses some very well thought-out features like docblock edit links (linking to github) and direct source links. The (generator)[https://github.com/yiisoft/yii2-apidoc] itself is most likely too Yii-specific though.
- [mamuz/PhpDependencyAnalysis](https://github.com/mamuz/PhpDependencyAnalysis)

**Comment by cisso** [comment]
phpDocumentor/Reflection doesn't do much by itself, but phpDocumentor2's [JsonpRenderer](https://github.com/phpDocumentor/phpDocumentor2/blob/acb4a19bf4814f694a496ff32f9b67e009a571c9/src/Application/Renderer/JsonpRenderer.php) looks interesting.

**Comment by cisso** [comment]
So far phpdox covers the requirements.

**Comment by mootari** [comment]
Switched to ApiGen due to superior API.
